---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "WPESA - Workshop on the Political Economy of South Asia"
keywords:    "Politics, South Asia, India, Pakistan, Political Economy"
description: "An online forum for early career researchers to share work on the political economy of South Asia, broadly defined."
source_link: "http://wpesa.net"
favicon:     "img/favicon.ico" 
touch_icon:  "img/apple-touch-icon.png" 
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#fffefc'
  navy:      '#302047'
  orange:    '#e98c14'
  teal:      '#37676a'
  gray:      '#a6a6a6'

kramdown:
  auto_ids:  false

